import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

In [4]:
# load dataset
flights_df = pd.read_csv("D:\\DL Project\\New folder\\Travel_Analytics_MLOps\\data\\raw\\flights.csv")

flights_df.head()

,travelCode,userCode,from,to,flightType,price,time,distance,agency,date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,09/26/2019
1,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,09/30/2019
2,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,10/03/2019
3,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,10/04/2019
4,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019

In [5]:
# check data types
flights_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271888 entries, 0 to 271887
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   travelCode  271888 non-null  int64
 1   userCode    271888 non-null  int64
 2   from        271888 non-null  object
 3   to          271888 non-null  object
 4   flightType  271888 non-null  object
 5   price       271888 non-null  float64
 6   time        271888 non-null  float64
 7   distance    271888 non-null  float64
 8   agency      271888 non-null  object
 9   date        271888 non-null  object
dtypes: float64(3), int64(2), object(5)
memory usage: 20.7+ MB

In [6]:
# convert date column
flights_df['date'] = pd.to_datetime(flights_df['date'])

In [7]:
# we have to verify it
flights_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271888 entries, 0 to 271887
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   travelCode  271888 non-null  int64
 1   userCode    271888 non-null  int64
 2   from        271888 non-null  object
 3   to          271888 non-null  object
 4   flightType  271888 non-null  object
 5   price       271888 non-null  float64
 6   time        271888 non-null  float64
 7   distance    271888 non-null  float64
 8   agency      271888 non-null  object
 9   date        271888 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 20.7+ MB

In [8]:
# to extract data features from data
flights_df['year'] = flights_df['date'].dt.year

flights_df['month'] = flights_df['date'].dt.month

flights_df['day'] = flights_df['date'].dt.day

flights_df['day_of_week'] = flights_df['date'].dt.day_name()

flights_df['week_of_year'] = flights_df['date'].dt.isocalendar().week.astype(int)

In [9]:
# drop original date
flights_df.drop(columns='date', inplace=True)

In [10]:
# check new dataset
flights_df.head()

,travelCode,userCode,from,to,flightType,price,time,distance,agency,year,month,day,day_of_week,week_of_year
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,2019,9,26,Thursday,39
1,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,2019,9,30,Monday,40
2,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,2019,10,3,Thursday,40
3,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,2019,10,4,Friday,40
4,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,2019,10,10,Thursday,41

Now we have all that:-
travelCode and userCode from to flightType, price, time ,distance, agency, year	month, day, day_of_week, week_of_year

next step is Encode Categorical Columns:-
from
to
flightType
agency
day_of_week
here we are going to use label encodeing

In [11]:
# Label Encoding
label_encoder = LabelEncoder()

categorical_columns = [
    'from',
    'to',
    'flightType',
    'agency',
    'day_of_week'
]

for column in categorical_columns:
    flights_df[column] = label_encoder.fit_transform(flights_df[column])

In [12]:
# verify it 
flights_df.head()

,travelCode,userCode,from,to,flightType,price,time,distance,agency,year,month,day,day_of_week,week_of_year
0,0,0,5,3,1,1434.38,1.76,676.53,1,2019,9,26,4,39
1,0,0,3,5,1,1292.29,1.76,676.53,1,2019,9,30,1,40
2,1,0,1,3,1,1487.52,1.66,637.56,0,2019,10,3,4,40
3,1,0,3,1,1,1127.36,1.66,637.56,0,2019,10,4,0,40
4,2,0,0,7,1,1684.05,2.16,830.86,0,2019,10,10,4,41

In [13]:
# seprate features and target
X = flights_df.drop('price', axis=1)

y = flights_df['price']

In [14]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
# scale numerical features
scaler = StandardScaler()

numeric_columns = [
    'time',
    'distance',
    'year',
    'month',
    'day',
    'week_of_year'
]

X_train[numeric_columns] = scaler.fit_transform(X_train[numeric_columns])

X_test[numeric_columns] = scaler.transform(X_test[numeric_columns])

In [17]:
X_train.to_csv("../data/processed/X_train_flight.csv", index=False)
X_test.to_csv("../data/processed/X_test_flight.csv", index=False)

y_train.to_csv("../data/processed/y_train_flight.csv", index=False)
y_test.to_csv("../data/processed/y_test_flight.csv", index=False)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [18]:
import os

print(os.getcwd())

d:\DL Project\New folder\Travel_Analytics_MLOps\notebooks\feature_engineering

In [19]:
import os

print(os.path.exists("../data/processed"))

False

In [20]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]
print(PROJECT_ROOT)

d:\DL Project\New folder\Travel_Analytics_MLOps

In [21]:
X_train.to_csv("../../data/processed/X_train_flight.csv", index=False)

X_test.to_csv("../../data/processed/X_test_flight.csv", index=False)

y_train.to_csv("../../data/processed/y_train_flight.csv", index=False)

y_test.to_csv("../../data/processed/y_test_flight.csv", index=False)