In [1]:
# importing all necessary libraries
# ===============================
# Data Manipulation
# ===============================
import pandas as pd
import numpy as np

# ===============================
# Data Visualization
# ===============================
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# ===============================
# Ignore Warnings
# ===============================
import warnings
warnings.filterwarnings("ignore")

# ===============================
# Display Settings
# ===============================
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# ===============================
# Set Plot Style
# ===============================
plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
# load all 3 dtasets:-

# Load Users Dataset
users_df = pd.read_csv("../data/raw/users.csv")

# Load Flights Dataset
flights_df = pd.read_csv("../data/raw/flights.csv")

# Load Hotels Dataset
hotels_df = pd.read_csv("../data/raw/hotels.csv")

In [3]:
# verify all loaded datasets
print("Users Dataset Shape :", users_df.shape)
print("Flights Dataset Shape :", flights_df.shape)
print("Hotels Dataset Shape :", hotels_df.shape)

Users Dataset Shape : (1340, 5)
Flights Dataset Shape : (271888, 10)
Hotels Dataset Shape : (40552, 8)

In [5]:
print(users_df.head())

   code company             name  gender  age
0     0    4You        Roy Braun    male   21
1     1    4You   Joseph Holsten    male   37
2     2    4You    Wilma Mcinnis  female   48
3     3    4You     Paula Daniel  female   23
4     4    4You  Patricia Carson  female   44

In [6]:
print(flights_df.head())

   travelCode  userCode                from                  to  flightType  \
0           0         0         Recife (PE)  Florianopolis (SC)  firstClass
1           0         0  Florianopolis (SC)         Recife (PE)  firstClass
2           1         0       Brasilia (DF)  Florianopolis (SC)  firstClass
3           1         0  Florianopolis (SC)       Brasilia (DF)  firstClass
4           2         0        Aracaju (SE)       Salvador (BH)  firstClass

     price  time  distance       agency        date
0  1434.38  1.76    676.53  FlyingDrops  09/26/2019
1  1292.29  1.76    676.53  FlyingDrops  09/30/2019
2  1487.52  1.66    637.56      CloudFy  10/03/2019
3  1127.36  1.66    637.56      CloudFy  10/04/2019
4  1684.05  2.16    830.86      CloudFy  10/10/2019

In [7]:
print(hotels_df.head())

   travelCode  userCode     name               place  days   price    total  \
0           0         0  Hotel A  Florianopolis (SC)     4  313.02  1252.08
1           2         0  Hotel K       Salvador (BH)     2  263.41   526.82
2           7         0  Hotel K       Salvador (BH)     3  263.41   790.23
3          11         0  Hotel K       Salvador (BH)     4  263.41  1053.64
4          13         0  Hotel A  Florianopolis (SC)     1  313.02   313.02

         date
0  09/26/2019
1  10/10/2019
2  11/14/2019
3  12/12/2019
4  12/26/2019

In [8]:
# basic info of datasets
def dataset_summary(df, dataset_name):
    print("=" * 70)
    print(f"Dataset : {dataset_name}")
    print("=" * 70)

    print("\nShape")
    print(df.shape)

    print("\nColumns")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

In [9]:
dataset_summary(users_df, "Users")

======================================================================
Dataset : Users
======================================================================

Shape
(1340, 5)

Columns
['code', 'company', 'name', 'gender', 'age']

Data Types
code        int64
company    object
name       object
gender     object
age         int64
dtype: object

Missing Values
code       0
company    0
name       0
gender     0
age        0
dtype: int64

Duplicate Rows
0

In [10]:
dataset_summary(flights_df, "Flights")

======================================================================
Dataset : Flights
======================================================================

Shape
(271888, 10)

Columns
['travelCode', 'userCode', 'from', 'to', 'flightType', 'price', 'time', 'distance', 'agency', 'date']

Data Types
travelCode      int64
userCode        int64
from           object
to             object
flightType     object
price         float64
time          float64
distance      float64
agency         object
date           object
dtype: object

Missing Values
travelCode    0
userCode      0
from          0
to            0
flightType    0
price         0
time          0
distance      0
agency        0
date          0
dtype: int64

Duplicate Rows
0

In [11]:
dataset_summary(hotels_df, "Hotels")

======================================================================
Dataset : Hotels
======================================================================

Shape
(40552, 8)

Columns
['travelCode', 'userCode', 'name', 'place', 'days', 'price', 'total', 'date']

Data Types
travelCode      int64
userCode        int64
name           object
place          object
days            int64
price         float64
total         float64
date           object
dtype: object

Missing Values
travelCode    0
userCode      0
name          0
place         0
days          0
price         0
total         0
date          0
dtype: int64

Duplicate Rows
0

In [12]:
users_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
code,1340.0,NaN,NaN,NaN,669.5,386.968991,0.0,334.75,669.5,1004.25,1339.0
company,1340,5,4You,453,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,1340,1338,Charlotte Johnson,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,1340,3,male,452,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,1340.0,NaN,NaN,NaN,42.742537,12.869779,21.0,32.0,42.0,54.0,65.0

In [13]:
flights_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
travelCode,271888.0,NaN,NaN,NaN,67971.5,39243.724665,0.0,33985.75,67971.5,101957.25,135943.0
userCode,271888.0,NaN,NaN,NaN,667.505495,389.523127,0.0,326.0,659.0,1011.0,1339.0
from,271888,9,Florianopolis (SC),57317,NaN,NaN,NaN,NaN,NaN,NaN,NaN
to,271888,9,Florianopolis (SC),57317,NaN,NaN,NaN,NaN,NaN,NaN,NaN
flightType,271888,3,firstClass,116418,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,271888.0,NaN,NaN,NaN,957.37503,362.31189,301.51,672.66,904.0,1222.24,1754.17
time,271888.0,NaN,NaN,NaN,1.421147,0.542541,0.44,1.04,1.46,1.76,2.44
distance,271888.0,NaN,NaN,NaN,546.955535,208.851288,168.22,401.66,562.14,676.53,937.77
agency,271888,3,Rainbow,116752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,271888,999,09/26/2019,1335,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
hotels_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
travelCode,40552.0,NaN,NaN,NaN,67911.794461,39408.199333,0.0,33696.75,67831.0,102211.25,135942.0
userCode,40552.0,NaN,NaN,NaN,666.963726,391.136794,0.0,323.0,658.0,1013.0,1339.0
name,40552,9,Hotel K,5094,NaN,NaN,NaN,NaN,NaN,NaN,NaN
place,40552,9,Salvador (BH),5094,NaN,NaN,NaN,NaN,NaN,NaN,NaN
days,40552.0,NaN,NaN,NaN,2.499679,1.119326,1.0,1.0,2.0,4.0,4.0
price,40552.0,NaN,NaN,NaN,214.439554,76.742305,60.39,165.99,242.88,263.41,313.02
total,40552.0,NaN,NaN,NaN,536.229513,319.331482,60.39,247.62,495.24,742.86,1252.08
date,40552,199,10/03/2019,404,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# check missing values in each dataset
print(users_df.isnull().sum())

code       0
company    0
name       0
gender     0
age        0
dtype: int64

In [18]:
print(flights_df.isnull().sum())

travelCode    0
userCode      0
from          0
to            0
flightType    0
price         0
time          0
distance      0
agency        0
date          0
dtype: int64

In [19]:
print(hotels_df.isnull().sum())

travelCode    0
userCode      0
name          0
place         0
days          0
price         0
total         0
date          0
dtype: int64

In [20]:
# check duplicate rows in each dataset
users_df.duplicated().sum()

np.int64(0)

In [21]:
flights_df.duplicated().sum()

np.int64(0)

In [22]:
hotels_df.duplicated().sum()

np.int64(0)

In [23]:
# to remove duplicate rows from each dataset
users_df = users_df.drop_duplicates()
flights_df = flights_df.drop_duplicates()
hotels_df = hotels_df.drop_duplicates()

In [24]:
# to verify the removal of duplicate rows
print(users_df.duplicated().sum())
print(flights_df.duplicated().sum())
print(hotels_df.duplicated().sum())

0
0
0

In [25]:
# check data types of each dataset
print(users_df.info())
print(flights_df.info())
print(hotels_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   code     1340 non-null   int64
 1   company  1340 non-null   object
 2   name     1340 non-null   object
 3   gender   1340 non-null   object
 4   age      1340 non-null   int64
dtypes: int64(2), object(3)
memory usage: 52.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271888 entries, 0 to 271887
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   travelCode  271888 non-null  int64
 1   userCode    271888 non-null  int64
 2   from        271888 non-null  object
 3   to          271888 non-null  object
 4   flightType  271888 non-null  object
 5   price       271888 non-null  float64
 6   time        271888 non-null  float64
 7   distance    271888 non-null  float64
 8   agency      271888 non-null  object
 9   date        271888 non-null  object
dtypes: float64(3), int64(2), object(5)
memory usage: 20.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40552 entries, 0 to 40551
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   travelCode  40552 non-null  int64
 1   userCode    40552 non-null  int64
 2   name        40552 non-null  object
 3   place       40552 non-null  object
 4   days        40552 non-null  int64
 5   price       40552 non-null  float64
 6   total       40552 non-null  float64
 7   date        40552 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 2.5+ MB
None

In [26]:
# /to check unique values in each column of the datasets
def check_unique_values(df, dataset_name):
    print(f"\n{'='*60}")
    print(f"Unique Values in {dataset_name}")
    print(f"{'='*60}")

    for column in df.columns:
        print(f"\nColumn: {column}")
        print(f"Unique Values: {df[column].nunique()}")

In [27]:
check_unique_values(users_df, "Users")

============================================================
Unique Values in Users
============================================================

Column: code
Unique Values: 1340

Column: company
Unique Values: 5

Column: name
Unique Values: 1338

Column: gender
Unique Values: 3

Column: age
Unique Values: 45

In [28]:
check_unique_values(flights_df, "Flights")

============================================================
Unique Values in Flights
============================================================

Column: travelCode
Unique Values: 135944

Column: userCode
Unique Values: 1335

Column: from
Unique Values: 9

Column: to
Unique Values: 9

Column: flightType
Unique Values: 3

Column: price
Unique Values: 490

Column: time
Unique Values: 33

Column: distance
Unique Values: 35

Column: agency
Unique Values: 3

Column: date
Unique Values: 999

In [29]:
check_unique_values(hotels_df, "Hotels")

============================================================
Unique Values in Hotels
============================================================

Column: travelCode
Unique Values: 40552

Column: userCode
Unique Values: 1310

Column: name
Unique Values: 9

Column: place
Unique Values: 9

Column: days
Unique Values: 4

Column: price
Unique Values: 9

Column: total
Unique Values: 36

Column: date
Unique Values: 199

In [30]:
# checking missing value percentage in each dataset
def missing_percentage(df):
    missing = pd.DataFrame({
        "Missing Values": df.isnull().sum(),
        "Percentage": (df.isnull().sum() / len(df)) * 100
    })

    return missing.sort_values("Percentage", ascending=False)

In [31]:
missing_percentage(users_df)

         Missing Values  Percentage
code                  0         0.0
company               0         0.0
name                  0         0.0
gender                0         0.0
age                   0         0.0

In [32]:
missing_percentage(flights_df)

            Missing Values  Percentage
travelCode               0         0.0
userCode                 0         0.0
from                     0         0.0
to                       0         0.0
flightType               0         0.0
price                    0         0.0
time                     0         0.0
distance                 0         0.0
agency                   0         0.0
date                     0         0.0

In [33]:
missing_percentage(hotels_df)

            Missing Values  Percentage
travelCode               0         0.0
userCode                 0         0.0
name                     0         0.0
place                    0         0.0
days                     0         0.0
price                    0         0.0
total                    0         0.0
date                     0         0.0

In [34]:
print(users_df.info())
print(flights_df.info())
print(hotels_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   code     1340 non-null   int64
 1   company  1340 non-null   object
 2   name     1340 non-null   object
 3   gender   1340 non-null   object
 4   age      1340 non-null   int64
dtypes: int64(2), object(3)
memory usage: 52.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271888 entries, 0 to 271887
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   travelCode  271888 non-null  int64
 1   userCode    271888 non-null  int64
 2   from        271888 non-null  object
 3   to          271888 non-null  object
 4   flightType  271888 non-null  object
 5   price       271888 non-null  float64
 6   time        271888 non-null  float64
 7   distance    271888 non-null  float64
 8   agency      271888 non-null  object
 9   date        271888 non-null  object
dtypes: float64(3), int64(2), object(5)
memory usage: 20.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40552 entries, 0 to 40551
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   travelCode  40552 non-null  int64
 1   userCode    40552 non-null  int64
 2   name        40552 non-null  object
 3   place       40552 non-null  object
 4   days        40552 non-null  int64
 5   price       40552 non-null  float64
 6   total       40552 non-null  float64
 7   date        40552 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 2.5+ MB
None